on: [push]

jobs:
  golang-cacheprog:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to GHCR
        run: |
          docker buildx create \
            --name container \
            --driver=docker-container \
            --use
          cd golang-cacheprog
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker buildx build \
            --cache-from=ghcr.io/${{ github.repository }}/golang-cacheprog-s3:_cache \
            --cache-to=ghcr.io/${{ github.repository }}/golang-cacheprog-s3:_cache \
            -t ghcr.io/${{ github.repository }}/golang-cacheprog-s3 \
            --push \
            -f Dockerfile .

    outputs:
      image: ghcr.io/${{ github.repository }}/golang-cacheprog-s3